export const SOCKET_PORT = 8000;

// Socket Messages
export const GET_DISPLAY_NAME = 'GET_DISPLAY_NAME';
export const SEARCH_USERS = 'SEARCH_USERS';
export const DISPLAY_NAME = 'DISPLAY_NAME';
export const GET_USERS = 'GET_USERS';
export const USERS = 'USERS';
export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CONNECT_TO_ROOM = 'CONNECT_TO_ROOM';
export const CONNECT_TO_ROOM_FAIL = 'CONNECT_TO_ROOM_FAIL';
export const USERS_CONNECTED = 'USERS_CONNECTED';
export const ROOM_STATUS = 'ROOM_STATUS';
export const SEND_ROOM_INVITES = 'SEND_ROOM_INVITES';
export const REJECT_TRANSFER_REQUEST = 'REJECT_TRANSFER_REQUEST';
export const ACCEPT_TRANSFER_REQUEST = 'ACCEPT_TRANSFER_REQUEST';

// Socket Messages Data
export const FULL_ROOM_MSG = 'Room Full';
export const INVALID_ROOM_MSG = 'Invalid Room';

// RTC SOCKET MESSAGES
export const ICE_CANDIDATE = 'ICE_CANDIDATE';
export const RTC_DESCRIPTION_OFFER = 'RTC_DESCRIPTION_OFFER';
export const RTC_DESCRIPTION_ANSWER = 'RTC_DESCRIPTION_ANSWER';