export const SOCKET_PORT = 8000;

// Socket Messages
export const GET_DISPLAY_NAME = 'GET_DISPLAY_NAME';
export const DISPLAY_NAME = 'DISPLAY_NAME';
export const GET_USERS = 'GET_USERS';
export const USERS = 'USERS';
export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CONNECT_TO_ROOM = 'CONNECT_TO_ROOM';
export const CONNECT_TO_ROOM_FAIL = 'CONNECT_TO_ROOM_FAIL';
export const ROOM_INFO = 'ROOM_INFO';

// Socket Messages Data
export const FULL_ROOM_MSG = 'Room Full';
export const INVALID_ROOM = 'Invalid Room';

// RTC SOCKET MESSAGES
export const ICE_CANDIDATE = 'ICE_CANDIDATE';
export const RTC_DESCRIPTION_OFFER = 'RTC_DESCRIPTION_OFFER';
export const RTC_DESCRIPTION_ANSWER = 'RTC_DESCRIPTION_ANSWER';

// FILE TRANSFER SOCKET MESSAGES
export const FILE_TRANSFER_REQUEST= 'FILE_INFO_REQUEST';
export const FILE_TRANSFER_REPLY= 'FILE_TRANSFER_REPLY';
